# @package _group_

learning_rate: 0.01
weight_decay: 0
lr_decay_gamma: 0.95
clip_norm: 5

n_epochs: 5

patience: 10

val_every_epoch: 1
save_every_epoch: 10
log_every_step: 10

progress_bar_refresh_rate: 1

log_offline: true
