# @package _group_

dataset: java-8k-asts
url: https://s3-eu-west-1.amazonaws.com/datasets.ml.labs.aws.intellij.net/code-summarization/java-full-asts.tar.gz

num_workers: 4

max_labels: 31000
max_label_parts: 7
max_tokens: 350000
max_token_parts: 5

max_tree_nodes: 250
max_tree_depth: 20

batch_size: 512
test_batch_size: 1024
