# @package _group_

name: java-small-typed-asts
url: https://s3-eu-west-1.amazonaws.com/datasets.ml.labs.aws.intellij.net/java-ast-methods/java-small-typed-asts.tar.gz

num_workers: 4

max_labels: 9000
max_label_parts: 7
max_tokens: 45000
max_token_parts: 5
max_types: 5500
max_type_parts: 5

max_tree_nodes: 250
max_tree_depth: 20

batch_size: 512
test_batch_size: 1024
