# @package _global_

defaults:
  - model: tree_lstm
  - datamodule: java_small
  - trainer: default

seed: 7
print_config: true

resume_checkpoint: null

data_folder: ../data

hydra:
  run:
    dir: .
  output_subdir: null
  job_logging: null
  hydra_logging: null
