data_folder: ../data/embeddings-for-trees/java-small-typed-asts

checkpoint: null

seed: 7
# Training in notebooks (e.g. Google Colab) may crash with too small value
progress_bar_refresh_rate: 1
print_config: true

wandb:
  project: TreeLSTM -- java-small
  group: null
  offline: false


data:
  url: https://s3.eu-west-1.amazonaws.com/datasets.ml.labs.aws.intellij.net/java-ast-methods/java-small-typed-asts.tar.gz

  num_workers: 4

  # 98.49% coverage
  labels_count: 10
  max_label_parts: 7
  # 97.44% coverage
  tokens_count: 1000
  max_token_parts: 5

  max_tree_nodes: 250
  max_tree_depth: 20

  batch_size: 512
  test_batch_size: 1024
  split_leaves: false

model:
  # Encoder
  embedding_size: 128
  encoder_dropout: 0.25
  encoder_size: 128

  # Decoder
  decoder_size: 320
  decoder_num_layers: 1
  rnn_dropout: 0.5

optimizer:
  lr: 0.01
  weight_decay: 0
  decay_gamma: 0.95

train:
  gpu: [0]
  n_epochs: 15
  patience: 15
  clip_norm: 10
  teacher_forcing: 1.0

  val_every_epoch: 1
  save_every_epoch: 1
  log_every_n_steps: 10